scale: 1e6
---
speedupFactor: 4500
---
planet: 
  id: 1
  name: 'Earth'
  color: 'blue'
  radius: 6.371e6
  mass: 5.972e24
  position:
    angle: 0
    value: 0
  velocity:
    angle: 0
    value: 0
  debug: false
---
planet: 
  id: 2
  name: 'Luna'
  color: 'red'
  radius: 1.737e6
  mass: 7.346e22
  position:
    angle: 90
    value: 3.844e8
  velocity:
    angle: 180
    value: 1.022e3
  debug: false
  