scale: 1.5e6
---
speedupFactor: 4500
---
planet: 
  id: 1
  name: 'Earth'
  color: 'green'
  radius: 6e6
  mass: 6e24
  position:
    angle: 90
    value: 3e8
  velocity:
    angle: 180
    value: 1.25e3
  debug: false
---
planet: 
  id: 2
  name: 'Earth'
  color: 'blue'
  radius: 6e6
  mass: 6e24
  position:
    angle: 0
    value: 3e8
  velocity:
    angle: 90
    value: 1.25e3
  debug: false
---
planet: 
  id: 3
  name: 'Earth'
  color: 'red'
  radius: 6e6
  mass: 6e24
  position:
    angle: 270
    value: 3e8
  velocity:
    angle: 0
    value: 1.25e3
  debug: false
---
planet: 
  id: 4
  name: 'Earth'
  color: 'purple'
  radius: 6e6
  mass: 6e24
  position:
    angle: 180
    value: 3e8
  velocity:
    angle: 270
    value: 1.25e3
  debug: false
  