scale: 0.6e9
---
speedupFactor: 4500
---
planet: 
  id: 1
  name: 'Sol'
  color: 'orange'
  radius: 0.6957e9
  mass: 1.989e30
  position:
    angle: 0
    value: 0
  velocity:
    angle: 0
    value: 0
  debug: false
---
planet: 
  id: 2
  name: 'Earth'
  color: 'blue'
  radius: 6.371e6
  mass: 5.972e24
  position:
    angle: 0
    value: 1.496e11
  velocity:
    angle: 90
    value: 3e4
  debug: false
